version: "3"
services:
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  web:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MIX_ENV=prod
      - PORT=80
      - DATABASE_URL=ecto://postgres:postgres@postgres/hello_world_prod
    ports:
      - "80:80"
